#!/bin/bash
echo Kopírování důležitých souborů
rm -r /var/www/html
mkdir /var/www/html
cp -r /usr/share/openexternalbuttons/files/html /var/www

echo Připravování databáze
mysql -e "CREATE DATABASE openexternalbuttons;"
mysql -e "use openexternalbuttons; CREATE TABLE loggedusers (id int(255) NOT NULL, userhash varchar(255) NOT NULL, username varchar(255) NOT NULL, loggedtime varchar(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;"
mysql -e "use openexternalbuttons; CREATE TABLE computers (id int(255) NOT NULL, name text NOT NULL, resetpin int(255) NOT NULL, powerpin int(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;"
mysql -e "use openexternalbuttons; CREATE TABLE users (id int(255) NOT NULL, username varchar(255) NOT NULL, password varchar(255) NOT NULL, permissions varchar(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;"
mysql -e "use openexternalbuttons; INSERT INTO users (id, username, password, permissions) VALUES (1, 'admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Administrator'), (2, 'user', 'e606e38b0d8c19b24cf0ee3808183162ea7cd63ff7912dbb22b5e803286b4446', 'User');"
mysql -e "use openexternalbuttons; ALTER TABLE computers ADD PRIMARY KEY (id);"
mysql -e "use openexternalbuttons; ALTER TABLE loggedusers ADD PRIMARY KEY (id);"
mysql -e "use openexternalbuttons; ALTER TABLE users ADD PRIMARY KEY (id);"
mysql -e "use openexternalbuttons; ALTER TABLE computers MODIFY id int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;"
mysql -e "use openexternalbuttons; ALTER TABLE loggedusers MODIFY id int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=34;"
mysql -e "use openexternalbuttons; ALTER TABLE users MODIFY id int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;"
mysql -e "use openexternalbuttons; COMMIT;"

echo Nastavování práv
chown -R www-data:www-data /var/www/html
chmod -R og-r /var/www/html

echo "www-data ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers
echo "www-data ALL=NOPASSWD /sbin/reboot" | tee -a /etc/sudoers

password=$(openssl rand -base64 8)
mkdir -p /etc/OEB
echo "$password" > /etc/OEB/dbpassword.txt
chown -R www-data:www-data /etc/OEB
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$password';"
mysql -e "FLUSH PRIVILEGES;" -p$password

adduser www-data gpio
adduser www-data netdev

echo "[Allow Wi-Fi management]
Identity=unix-user:www-data
Action=org.freedesktop.NetworkManager.*
ResultAny=yes
ResultInactive=yes
ResultActive=yes" | tee /etc/polkit-1/localauthority/50-local.d/10-network-manager.pkla

sudo raspi-config nonint do_wifi_country CZ

echo Restartování služeb
systemctl restart polkit
systemctl restart mysqld
systemctl restart apache2
